import 'package:get/get.dart';

class TicketsController extends GetxController {
  // Static dummy data with added nationality, contact details, and ticket breakdown
  final RxList<Map<String, dynamic>> myTickets = <Map<String, dynamic>>[
    {
      'orderId': 'ORD_10098273',
      'bookingDate': '2024-05-12',
      'visitDate': '2024-05-15',
      'attractionName': 'Pratap Gourav Kendra',
      'totalAmount': 920.00,
      'ticketCount': 4,
      'status': 'Upcoming',
      'customerName': 'xyz',
      'email': 'xyz@example.com',
      'phone': '+91 747589035',
      'nationality': 'Indian',
      'adultCount': 2,
      'childCount': 1,
      'infantCount': 1,
    },
    {
      'orderId': 'ORD_10098200',
      'bookingDate': '2024-02-16',
      'visitDate': '2024-02-18',
      'attractionName': 'Combo (P.G.K. + Water Show)',
      'totalAmount': 1240.00,
      'ticketCount': 5,
      'status': 'Visited',
      'customerName': 'Test User',
      'email': 'test.user@example.com',
      'phone': '+91 983410008',
      'nationality': 'Indian',
      'adultCount': 3,
      'childCount': 2,
      'infantCount': 0,
    },
    {
      'orderId': 'ORD_10098155',
      'bookingDate': '2023-12-05',
      'visitDate': '2023-12-10',
      'attractionName': 'Water Laser Show Only',
      'totalAmount': 320.00,
      'ticketCount': 2,
      'status': 'Visited',
      'customerName': 'John Doe',
      'email': 'john.doe@example.com',
      'phone': '+1 415-555-0198',
      'nationality': 'Foreigner',
      'adultCount': 2,
      'childCount': 0,
      'infantCount': 0,
    },
  ].obs;
}