// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQSNP7ldRHJeqIWqidYhrmAeUqzz4c24',
    appId: '1:1028857718377:web:b2d6540ec8e074180c24f8',
    messagingSenderId: '1028857718377',
    projectId: 'pgk-ticket-app',
    authDomain: 'pgk-ticket-app.firebaseapp.com',
    storageBucket: 'pgk-ticket-app.firebasestorage.app',
    measurementId: 'G-16DRSMT0MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_QryU65VyzCi1V6YXaqdTdzD0nuxy5Q',
    appId: '1:1028857718377:android:76af53955fc738800c24f8',
    messagingSenderId: '1028857718377',
    projectId: 'pgk-ticket-app',
    storageBucket: 'pgk-ticket-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7NyqciANd49gyOSdfKaREAveBKJBGR0',
    appId: '1:1028857718377:ios:16c4aadacf6b9a6c0c24f8',
    messagingSenderId: '1028857718377',
    projectId: 'pgk-ticket-app',
    storageBucket: 'pgk-ticket-app.firebasestorage.app',
    iosClientId: '1028857718377-h141n1rdqj718rmt5kbpgt4mom5vqg1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.pgkTicketApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7NyqciANd49gyOSdfKaREAveBKJBGR0',
    appId: '1:1028857718377:ios:16c4aadacf6b9a6c0c24f8',
    messagingSenderId: '1028857718377',
    projectId: 'pgk-ticket-app',
    storageBucket: 'pgk-ticket-app.firebasestorage.app',
    iosClientId: '1028857718377-h141n1rdqj718rmt5kbpgt4mom5vqg1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.pgkTicketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQSNP7ldRHJeqIWqidYhrmAeUqzz4c24',
    appId: '1:1028857718377:web:be5c1fd6ab9ba7100c24f8',
    messagingSenderId: '1028857718377',
    projectId: 'pgk-ticket-app',
    authDomain: 'pgk-ticket-app.firebaseapp.com',
    storageBucket: 'pgk-ticket-app.firebasestorage.app',
    measurementId: 'G-W3XGV8NJCN',
  );
}
